" My vim settings file
" Author: Mskadu <mskadu@gmail.com>
" Last updated: 03/03/2017
"

set nocompatible                "chose not to be compatible with legacy vi
if version >= 600
  syntax enable

  if version >= 700
    filetype plugin indent on
  else
    filetype on
    filetype plugin on
    filetype indent on
  endif
else
  :finish
endif

" Read and write properly with Unicode
" See: http://vim.wikia.com/wiki/Working_with_Unicode
if has("multi_byte")            
  if &termencoding == ""
    let &termencoding = &encoding
  endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  "setglobal bomb
  set fileencodings=ucs-bom,utf-8,latin1
endif

set autoindent                  " continue indenting when moving to new line
set ruler                       " set line/col of current cursor position
set showcmd                     " show incomplete commands
set showmatch                   " show matching brackets
set showmode                    " show current mode (insert, etc) in last line
set backspace=indent,eol,start  " backspace through it all in Insert mode
set formatoptions=croq          " auto-wrap text, continue and format comments
set number                      " show line number for each line
set smartindent                 " smart indenting when starting new line
set tabstop=2 shiftwidth=2      " a tab is 2 spaces
set expandtab                   " use spaces, not tabs
set ls=2                        " show status line
set statusline=%<%f%h%m%r%=%b\ 0x%B\ \ %l,%c%V\ %P " modify status line to show charcode at cursor 
set nobackup                    " no *.bak files
set writebackup                 " keep backup while before writing file 
set nowrap                      " don't wrap text
set nohlsearch                  " don't highlight searches
"set verbose=9                  " turn this on when you want to debug
set cursorline                  " highlight current cursor line


"Fix findstr for Win32
if has("win32")
  set grepprg=findstr\ /R\ /S\ /N
endif

" Choose right syntax highlighting with tab completion
map <F2> :source $VIMRUNTIME/syntax/
" F9 toggles highlighting
map <F9> :if has("syntax_items")<CR>syntax off<CR>else<CR>syntax on<CR>endif<CR><CR>

"Vim 7 specific mappings
if version >= 700
  map <C-t> <Esc>:tabnew<CR>
  map <C-F4> <Esc>:tabclose<CR> 
  map <C-a> <Esc>ggVG 
endif

" Windows specific mappings
if has("win32")
  "Ctrl+A = Select All
  map <C-a> <Esc>ggVG 
  "Ctrl+tab = Fwd Cycle across splits
  map <C-Tab> <Esc><C-w>w
  "Ctrl+Shift+tab = Reverse Cycle across splits
  map <C-S-Tab> <Esc><C-w>W
endif

" Reload settings file everytime its written 
" Note: replace $VIM/.vimrc with wherever your vimrc lives
autocmd! bufwritepost _vimrc source $VIM/_vimrc         
autocmd! bufwritepost .vimrc source $VIM/.vimrc

"autocmd BufRead,BufNewFile *.java set makeprg=javac\ %
"autocmd BufRead BufNewFile *.java set makeprg=ant\ -emacs

" From vimrc_example. I like this!

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$") |
      \   exe "normal! g`\"" |
      \ endif


"Abbreviations
:iabbrev @@   mskadu@gmail.com

colorscheme desert

"Make GVim look a bit better on Windows
if has("gui") 
  if has("win32")
    set guifont=Courier_New:h9:cANSI
  endif

  "see: http://vim.wikia.com/wiki/VimTip1
  set mousemodel=extend
endif
